version: 2

jobs:

  # Define a "build_test" job to be run with Circle
  build_test:
  
    # This is the base environment that Circle will use
    docker:
      - image: frolvlad/alpine-miniconda3
      
    steps:
    
      - run: apk add --no-cache build-base ca-certificates git openssh bash curl
      
      # Get our data and merge with upstream
      - checkout
      
      # Restore cached files to speed things up
      - restore_cache:
          keys:
            - conda-pkgs
            
      - run: ./ci/install-circleci.sh
      
      # Cache some files for a speedup in subsequent builds
      - save_cache:
          key: conda-pkgs
          paths:
            - /opt/conda/pkgs
            
      # Run tests
      - run:
           name: Running Tests 
           command: source activate esmlab-dev && py.test --junitxml=test-reports/junit.xml --cov=./

      - run:
           name: Coverage
           command: source activate esmlab-dev && codecov
           when: on_success
           
     

# Tell CircleCI to use this workflow
workflows:
  version: 2
  default:
    jobs:
      - build_test