package:
   name: esmlab
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..
git:
  depth: false

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - python
    - xarray
    - cftime
    - dask

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest --verbose

about:
  home: https://github.com/NCAR/esmlab
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Tools for working with earth system multi-model analyses with xarray. 