{% set name = "esmlab" %}
{% set version = "0.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/NCAR/esmlab/archive/v{{ version }}.tar.gz
  

build: 
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python
  number: 0

requirements:

  build:
    - python

  run:
    - python
    - xarray
    - cftime
    - dask

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - esmlab
  commands:
    - pytest --verbose

about:
  
  home: https://github.com/NCAR/esmlab
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Tools for working with earth system multi-model analyses with xarray. 
  dev_url: https://github.com/NCAR/esmlab
  doc_url: https://esmlab.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - kmpaul