name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - python=2.7
  - numpy
  - xarray
  - matplotlib
  - netcdf4
  - zarr
  - dask
  - distributed
  - pytest
  - coverage
  - pytest-cov
  - codecov
  


