name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - coverage
  - dask
  - distributed
  - matplotlib
  - netcdf4
  - numpy
  - pytest
  - pytest-cov
  - python=3.6
  - xarray
  - xarray-extras
  - zarr