name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - coverage
  - dask
  - distributed
  - esmpy
  - git
  - ipykernel
  - matplotlib
  - netcdf4
  - numpy
  - pytest
  - pytest-cov
  - python=3.6
  - scipy
  - xesmf
  - zarr
  - pip:
    - pytest-lazy-fixture
    - git+https://github.com/pydata/xarray.git
