name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - coverage
  - dask
  - distributed
  - matplotlib
  - netcdf4
  - numpy
  - pytest
  - pytest-cov
  - python=2.7
  - xarray
  - zarr
  


