name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - codecov
  - coverage
  - dask
  - distributed
  - esmpy
  - flake8
  - git
  - ipykernel
  - isort
  - matplotlib
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pytest
  - pytest-cov
  - python=3.7
  - recommonmark
  - scipy
  - sphinx_rtd_theme
  - sphinx>=1.6
  - xesmf
  - zarr
  - pip:
    - pytest-lazy-fixture
    - sphinx_copybutton
    - git+https://github.com/pydata/xarray.git
