name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - bottleneck
  - codecov
  - dask
  - distributed
  - esmpy
  - flake8
  - git
  - ipykernel
  - isort
  - make
  - matplotlib
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc=0.8.0
  - pip
  - pytest
  - pytest-cov
  - python=3.7
  - recommonmark
  - scipy
  - sphinx_rtd_theme=0.4.2
  - sphinx>=1.6
  - tornado
  - xarray>=0.12
  - xesmf
  - zarr
  - pip:
    - pytest-lazy-fixture
    - sphinx_copybutton
    - pytest-xdist
    - git+https://github.com/NCAR/esmlab-regrid.git
