name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - coverage
  - dask
  - distributed
  - esmpy
  - ipykernel
  - matplotlib
  - netcdf4
  - numpy==1.15
  - pytest
  - pytest-cov
  - python=3.6
  - xarray==0.11.3
  - xesmf
  - zarr
  - pip:
    - pytest-lazy-fixture
