name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - bottleneck
  - codecov
  - dask
  - esmpy
  - ipykernel
  - make
  - netcdf4
  - numpy
  - pandoc==1.19
  - pip
  - pytest
  - pytest-cov
  - python=3.7
  - scipy
  - xesmf
  - cftime==1.0.3.4
  - pip:
    - pytest-lazy-fixture
    - pytest-xdist
    - xskillscore
    - docrep
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/NCAR/esmlab-regrid.git
