name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - coverage
  - dask
  - distributed
  - git
  - matplotlib
  - netcdf4
  - numpy
  - pytest
  - pytest-cov
  - python=2.7
  - scipy
  - zarr
  - pip:
    - pytest-lazy-fixture
    - contextlib2
    - xarray>=0.11.2
