name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - bottleneck
  - codecov
  - dask
  - esmpy
  - netcdf4
  - numpy
  - pip
  - pytest
  - pytest-cov
  - python=3.6
  - scipy
  - xarray>=0.12
  - xesmf
  - pre_commit
  - cftime==1.0.3.4
  - pip:
    - pytest-lazy-fixture
    - pytest-xdist
    - xskillscore
    - docrep
    - git+https://github.com/NCAR/esmlab-regrid.git
