name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - python=2.7
  - numpy==1.15
  - xarray
  - matplotlib
  - netcdf4
  - zarr
  - dask
  - distributed
  - pytest
  - coverage
  - pytest-cov
  - codecov
  - pip:
    - pytest-lazy-fixture
  


