name: esmlab-dev
channels:
  - conda-forge
dependencies:
  - ipython
  - nbsphinx
  - numpydoc=0.8.0
  - dask
  - pip
  - python=3.7
  - recommonmark
  - sphinx_rtd_theme=0.4.2
  - sphinx=1.8.2
  - sphinx-copybutton=0.2.5
  - esmpy
  - bottleneck
  - scipy
  - make
  - pip:
    - git+https://github.com/NCAR/esmlab-regrid.git
