name: esmlab
channels:
  - conda-forge
  - default
dependencies:
  - python=3.6
  - numpy 
  - dask 
  - distributed 
  - zarr 
  - xarray
  - importnb 
  - pytest 
  - pytest-cov 
  - netcdf4
  - numcodecs
  - jupyterlab
  - python-blosc
  - lz4
  - nbserverproxy
  - click
  - flake8
  - pip:
    - version-information 
